### ISSUE TITLE
Position of ParameterInit

### ISSUE THREAD

**Issue by neveling** [padsley/k600analyser#111]
At present ParameterInit is issued inside
main_init                    
which means during adc_init the value of ADCModules is not available. So during the definition
of the ADC2DModules the software thinks there are no ADCModules since the value is not yet set.
However, by the time we get to the ADCevent the correct value for ADCModules was established,causing a seg fault when trying to fill a histogram that was not defined.

The core of the issue is where we place Parameterinit.

I have moved it to the init routine in analyzer.c

Let see how that goes...

**Comment by padsley** [comment]
This has been done and nothing appears to be borked. Closing.
