### ISSUE TITLE
RAW data: ADC channel values also needed

### ISSUE THREAD

**Issue by neveling** [padsley/k600analyser#120]
I think it would be useful if the ADC channel nrs and module nrs are also given in the raw data.

**Comment by neveling** [comment]
What an idiotic thing to say. 
And I am not even on night shift.
Please ignore

**Comment by neveling** [comment]
after thinking another few secs, I am confused again

**Comment by padsley** [comment]
http://xkcd.com/1695/

**Comment by neveling** [comment]
I have now convinced myself that it is a good thing to have ADC channels as a separate array as well. See the attached picture. This is a quick way to see which ADC channels belong to a particular detector. The draw cmd was as follows:

DATA->Draw("ADCValues[60]:ADCChannels>>h(130,0,130,100,300,4000)","ADCValues>700","col")

![adcvalue-vs-adcchan](https://cloud.githubusercontent.com/assets/8490543/16193154/ced22c9e-36ed-11e6-816e-8a44da2ff08d.png)

**Comment by padsley** [comment]
I can't sleep...

Has this been implemented in the master branch? If so, can the issue be closed?

**Comment by neveling** [comment]
Indeed it is implemented.
Will close this issue
