### ISSUE TITLE
PR226 Branch

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#13]
Set up a branch for the PR226 sort code for reference purposes.

**Comment by neveling** [comment]
It may very well be that the PR226dev branch can be merged with this one. Since I think this branch was left untouched since its creation and is therefore not so useful.
I just did not want to bugger up something, so I first tried a new branchname...

**Comment by padsley** [comment]
I don't know whether this is still open but Kevin is dealing with PR226 data so I don't think that I need this issue anymore. Closing.
