### ISSUE TITLE
Problem running analyser at York

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#130]
[ODBEdit,ERROR] [system.c:719:ss_shm_open,ERROR] Cannot create shared memory segment '/Default_ODB_SHM', shm_open() errno 13 (Permission denied)

**Comment by padsley** [comment]
Uh. Was computer-dependent. Fixed it by running it elsewhere. ¯\_(ツ)_/¯

**Comment by nichubbard** [comment]
I think this issue is the computer needs $MIDAS_DIR to be set to a directory which is writeable. I am guessing by default it's trying to put it in / which is not writeable on York machines.
