### ISSUE TITLE
.gitignore files

### ISSUE THREAD

**Issue by nichubbard** [padsley/k600analyser#134]
I added a .gitignore file into the PR264 branch, which means git will ignore the .so files etc created during compilation, so you won't them showing up with `git status` or added if you do something lazy like `git add *`. It's probably worth adding it to other branches too. Any branches other than master still in significant use that may benefit?

**Comment by padsley** [comment]
Uh. Probably. I'd say do it for PR254, 264, 238_2016, 259. Those are the experiments this year. And nai_vicente.

**Comment by nichubbard** [comment]
The branches PR254 and 259 don't seem to exist. Done for the rest.
