### ISSUE TITLE
Weird X1pos due to hot wires?

### ISSUE THREAD

**Issue by nichubbard** [padsley/k600analyser#142]
Looking at Run #1085 from PR264 the graph at approx 425mm looks very weird, which *seems* to be due to some hot TDC wires. Phil has had a quick look at the code whilst he's at York and we're stuck. There is a function to remove the hot wires but that doesn't seem to be called - and we're not sure why.

Comments, suggestions?
![weirdx1](https://cloud.githubusercontent.com/assets/9157300/18750483/2e96110c-80d3-11e6-9c56-77af3cf4ac49.png)

**Comment by nichubbard** [comment]
![weirdtdc](https://cloud.githubusercontent.com/assets/9157300/18751038/695b3aa4-80d5-11e6-8599-dc0a7eaa641b.png)

**Comment by neveling** [comment]
Mmm, not nice.
Will look at it first thing tomorrow.

**Comment by nichubbard** [comment]
The problem seems to have been solved by deleting "<<<<<HEAD" from the first line of CableLength.dat. How it appeared and didn't cause crashes I do not know.

**Comment by padsley** [comment]
Hi. @nichubbard, could you make sure that the PR264 online version is updated with the right files (i.e. without <<<<<<<<<<<<<<<<<<<<<<<<<<<HEAD included). Just in case someone else ever needs to use that version of the analyser.
