### ISSUE TITLE
new method to version data and version source... 

### ISSUE THREAD

**Issue by gauss345** [padsley/k600analyser#171]
Hi,

So I've been using this tool, [dvc](https://dvc.org/), for some of my legacy projects with this repo, to keep track of the .mid files, and the source I'm using to analyze it, and results. 

The project is a machine learning project, but I don't see why, it cannot be extended for just regular root scripts etc.

Just an alternative idea to versioning, that uses git to keep track of the .mid files and the versions of that, and keep track of what script/source you used with that data. 

Might be useful for some, on small projects. 

Lee

**Comment by padsley** [comment]
Closing this issue to tidy things up. I still need to look into this, may do so while I'm living in my hovel.
