### ISSUE TITLE
HagarData Class

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#4]
Need to write the HagarData class for the analyser. Should include the averaging between the PMTs and some diagnostics about that.

**Comment by neveling** [comment]
I am having troubles creating the shared library 
HagarData_c.so
As per the example of SiliconData, I would think I am doing everything correct.
...but obviously not since I have no joy...
Time for a coffee...

**Comment by neveling** [comment]
Info in <TUnixSystem::ACLiC>: creating shared library /home/neveling/K600/PR226-Retief-16O/ANALYSIS/./HagarData_c.so
/home/neveling/K600/PR226-Retief-16O/ANALYSIS/HagarData_c_ACLiC_dict.o: In function `HagarData::SetEnergy(float*)':
HagarData_c_ACLiC_dict.cxx:(.text+0xf67): undefined reference to `HagarOffset'
HagarData_c_ACLiC_dict.cxx:(.text+0xf6e): undefined reference to `HagarGain'
/home/neveling/K600/PR226-Retief-16O/ANALYSIS/HagarData_c_ACLiC_dict.o: In function `HagarDataSort(float*, int, int*, float*)':
HagarData_c_ACLiC_dict.cxx:(.text+0x1079): undefined reference to `multiTDC::multiTDC(int, int*, float*)'
HagarData_c_ACLiC_dict.cxx:(.text+0x1080): undefined reference to `HagarADCChannels'
HagarData_c_ACLiC_dict.cxx:(.text+0x114e): undefined reference to `multiTDC::SizeOfEvent()'
HagarData_c_ACLiC_dict.cxx:(.text+0x119a): undefined reference to `HagarTDCChannels'
HagarData_c_ACLiC_dict.cxx:(.text+0x11ba): undefined reference to `multiTDC::SizeOfEvent()'
/home/neveling/K600/PR226-Retief-16O/ANALYSIS/HagarData_c_ACLiC_dict.o: In function `G__cpp_setup_globalHagarData_c_ACLiC_dict':
HagarData_c_ACLiC_dict.cxx:(.text+0x1893): undefined reference to `ADCsize'
HagarData_c_ACLiC_dict.cxx:(.text+0x18dd): undefined reference to `HagarADCChannels'
HagarData_c_ACLiC_dict.cxx:(.text+0x1927): undefined reference to `HagarTDCChannels'
collect2: error: ld returned 1 exit status
Error in <ACLiC>: Compilation failed!

**Comment by padsley** [comment]
The HagarData class is now replaced by GammaData and HagarSort. Closing the issue as this is no longer a problem.
