### ISSUE TITLE
Master branch

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#71]
@pellegri has noted that the master branch doesn't compile.

This problem has been noted before.

It's due to a mistake that I've made in the definition of PulseLimits.

I need to fix it at some point. This is a note to remind me to fix it.

**Comment by padsley** [comment]
I can't reproduce this error on my laptop.

If someone else could try compiling the master branch to see if it produces an error and could then post the log here, I'd be grateful.

**Comment by padsley** [comment]
I merged the fixed version of SetupDev that Alex forked back into the master as it went in there easily and probably is sufficient for what anyone might need.

This means that the master branch should be the version using .cfg files that I have been setting up on arthur at iThemba.

**Comment by neveling** [comment]
Sorry I am a bit late
Anyway,  I compiled it with not problems, no errors

R

**Comment by padsley** [comment]
Grand.

I'm going to assume in lieu of any comments to the contrary that the master branch is a fully armed and operational battle station.
