### ISSUE TITLE
Set VDC configuration from config file

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#83]
Should ensure that this is working. It's currently a bodge.

**Comment by padsley** [comment]
Doh. This is also issue #94. Argh. I should really get onto this.

**Comment by neveling** [comment]
I can confirm that the choice in the config file makes its way to main.c, specificaly to the init routine
main_init.

extern bool VDC1_new, VDC2_new;

if(VDC1_new)
{
if(VDC2_new)
{
setupchannel2wireXUXU(Channel2Wire);
}
else
{
setupchannel2wireXUXold(Channel2Wire);
}
}
else
{
if(VDC2_new)
{
setupchannel2wireXoldXU(Channel2Wire);
}
else
{
setupchannel2wireXoldXold(Channel2Wire);
}
}

All four these setupchannel2wire routines are in Focalplane.c
