### ISSUE TITLE
VDC Choice

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#94]
We need to make sure that the VDC choice in the config file is actually being chosen in the code.

Is it?

**Comment by neveling** [comment]
I can confirm that the choice in the config file makes its way to main.c, specificaly to the init routine 
main_init.

   extern bool VDC1_new, VDC2_new;

   if(VDC1_new)
     {
       if(VDC2_new)
	 {
 	   setupchannel2wireXUXU(Channel2Wire);
	 }
       else
	 {
 	   setupchannel2wireXUXold(Channel2Wire);
	 }
     }
   else
     {
       if(VDC2_new)
	 {
 	   setupchannel2wireXoldXU(Channel2Wire);
	 }
       else
	 {
	   setupchannel2wireXoldXold(Channel2Wire);
	 }
     }


All four these setupchannel2wire routines are in Focalplane.c
